//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TiendaEntities : DbContext
    {
        public TiendaEntities()
            : base("name=TiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_crearEditarProducto_Result> sp_crearEditarProducto(Nullable<int> idProducto, string nombreProducto, Nullable<decimal> valorUnitario, string image)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("nombreProducto", nombreProducto) :
                new ObjectParameter("nombreProducto", typeof(string));
    
            var valorUnitarioParameter = valorUnitario.HasValue ?
                new ObjectParameter("valorUnitario", valorUnitario) :
                new ObjectParameter("valorUnitario", typeof(decimal));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_crearEditarProducto_Result>("sp_crearEditarProducto", idProductoParameter, nombreProductoParameter, valorUnitarioParameter, imageParameter);
        }
    
        public virtual ObjectResult<sp_obtenerProductos_Result> sp_obtenerProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtenerProductos_Result>("sp_obtenerProductos");
        }
    
        public virtual ObjectResult<sp_crearEditarCliente_Result> sp_crearEditarCliente(Nullable<int> idCliente, string cedula, string nombre, string apellido, string telefono)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_crearEditarCliente_Result>("sp_crearEditarCliente", idClienteParameter, cedulaParameter, nombreParameter, apellidoParameter, telefonoParameter);
        }
    
        public virtual ObjectResult<sp_crearEditarDetalleVenta_Result> sp_crearEditarDetalleVenta(Nullable<int> idVenta, Nullable<int> idDetalleVenta, Nullable<int> idProducto, Nullable<decimal> valorUnitario)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var idDetalleVentaParameter = idDetalleVenta.HasValue ?
                new ObjectParameter("idDetalleVenta", idDetalleVenta) :
                new ObjectParameter("idDetalleVenta", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var valorUnitarioParameter = valorUnitario.HasValue ?
                new ObjectParameter("valorUnitario", valorUnitario) :
                new ObjectParameter("valorUnitario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_crearEditarDetalleVenta_Result>("sp_crearEditarDetalleVenta", idVentaParameter, idDetalleVentaParameter, idProductoParameter, valorUnitarioParameter);
        }
    
        public virtual ObjectResult<sp_crearEditarVenta_Result> sp_crearEditarVenta(Nullable<int> idVenta, Nullable<int> idCliente, Nullable<decimal> valorTotal)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var valorTotalParameter = valorTotal.HasValue ?
                new ObjectParameter("valorTotal", valorTotal) :
                new ObjectParameter("valorTotal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_crearEditarVenta_Result>("sp_crearEditarVenta", idVentaParameter, idClienteParameter, valorTotalParameter);
        }
    
        public virtual ObjectResult<sp_obtenerCliente_Result> sp_obtenerCliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtenerCliente_Result>("sp_obtenerCliente", idClienteParameter);
        }
    
        public virtual ObjectResult<sp_obtenerDetalleVentas_Result> sp_obtenerDetalleVentas(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtenerDetalleVentas_Result>("sp_obtenerDetalleVentas", idVentaParameter);
        }
    
        public virtual ObjectResult<sp_obtenerVentas_Result> sp_obtenerVentas(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_obtenerVentas_Result>("sp_obtenerVentas", idClienteParameter);
        }
    }
}
